### ISSUE TITLE
[Feature]: Black Navigation Bar sollte sticky sein für mehr Orientierung

### ISSUE THREAD

**Issue by ghost** [meodai/raumgleiter#124]
## Issue
Man verliert sich komplett vor allem bei den Projekten und kann nicht mehr zurück oder auf home. Der schwarze Navigationsbalken oben sollte sticky sein so dass man immer wieder zurück kann und die Orientierung behält.

**Comment by meodai** [comment]
https://github.com/meodai/raumgleiter/pull/157/commits/047ffc83c805cabbaf873a57899a71af612dc8f2
