### ISSUE TITLE
[Enhancement]: Add layer on top of iframe

### ISSUE THREAD

**Issue by jorisnoo** [meodai/raumgleiter#131]
Steps to reproduce:
1. Go to https://raumgleiter.netlify.app/fr/projets/claraturm
2. scroll down with mouse
→ you'll get stuck "zooming" into the iframe

Expected:
I should be able to scroll down

Maybe only ativate the iframe on click?

**Comment by meodai** [comment]
Design: https://lukas110381.invisionapp.com/console/raumgleiter-1.1-ckhoy6pl006pr018jdqoob757/ckhoy6w4z06pw018ja4fw46gb/play#project_console

**Comment by jorisnoo** [comment]
@meodai Gibt es verschiedene icons zur Auswahl?

**Comment by lukasmettler** [comment]
Ja, Play und Interactive.

**Comment by jorisnoo** [comment]
@lukasmettler Danke!
@meodai Kannst du mir bescheid geben, sobald du die svg files bereit hast?

**Comment by lukasmettler** [comment]
Hi Joris

Ok, wenn ich sie an die Mail anfüge?

Lieber Gruss, Lukas





Lukas Mettler
Brand Designer
+41 079 776 18 86

lucmettler.com GmbH
Neumarkt 17
8001 Zürich

**Comment by jorisnoo** [comment]
@lukasmettler So habe ich sie leider nicht erhalten; du müsstest mir die Icons direkt per mail an meine Adresse schicken

**Comment by basgys** [comment]
@jorisnoo `iframe.icon` is currently empty, so I've added a placeholder. @meodai Perhaps we could replace it with the svg shown on the design.

![Screenshot 2021-01-19 at 20 20 39](https://user-images.githubusercontent.com/491123/105083355-11c9d900-5a95-11eb-8335-eda0ee6db39b.png)

**Comment by meodai** [comment]
awesome! @basgys I will replace it with the correnct one

**Comment by meodai** [comment]
U added the icon
