### ISSUE TITLE
[New Feature]: Sound bei Projektvideos

### ISSUE THREAD

**Issue by ghost** [meodai/raumgleiter#135]
## Issue
**Describe the bug**
Bei den Projekten sollte es möglich sein, Sound einzuschalten, z.B. https://raumgleiter.netlify.app/projekte/shoppi-tivoli-spreitenbach
Kann durch Userinteraction geschehen, da automatischer Sound ja nicht möglich ist. Eigentlich wärs fast am Besten, wenn man bei einer solchen Animation zuerst bewusst den Playbutton drücken müsste, dann startet es gleich mit Sound

**Comment by jorisnoo** [comment]
@meodai Die Tonspur ist aktiviert im Video im Projekt `pilatusarena-kriens`

**Comment by jorisnoo** [comment]
Ungestylter mute button ist in `components/VimeoEmbed.vue`

**Comment by meodai** [comment]
icon ist gestyled, wie besprochen fehlt noch der state
