### ISSUE TITLE
[Feat] Impressum: Add link to footer

### ISSUE THREAD

**Issue by meodai** [meodai/raumgleiter#152]
And move the language selection: https://lukas110381.invisionapp.com/console/raumgleiter-1.1-ckhoy6pl006pr018jdqoob757/ckhoy6w4z06pu018ja18vbryd/play

**Comment by jorisnoo** [comment]
Seite ist vorbereitet unter `/pages/imprint.vue` im branch `feature/release-1.1`

**Comment by basgys** [comment]
> Seite ist vorbereitet unter `/pages/imprint.vue` im branch `feature/release-1.1`

```js
    paths: {
      de: '/impressum',
      fr: '/imprimer',
      en: '/imprint',
    },
```

Impressum is a Swiss-specific legal term and does not require translations. `imprimer` does not sound correct to me, and since it is a latin word, I would keep it as is in french.

**Comment by jorisnoo** [comment]
@basgys In that case yes, please adjust it as you see fir. Thanks!
