### ISSUE TITLE
[Feat] Project Search

### ISSUE THREAD

**Issue by meodai** [meodai/raumgleiter#154]
Add a search function to projects: https://lukas110381.invisionapp.com/console/raumgleiter-1.1-ckhoy6pl006pr018jdqoob757/ckhoy6w4z06pu018ja18vbryd/play

**Comment by jorisnoo** [comment]
@meodai Ich habe ein ungestyltes suchfeld input field oberhalb der filter eingefügt (`ProjectSearchbar.vue`)
